/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<Integer> row = Arrays.asList(1, 1, 1, 1, 0, 1, 0, 0);

        ArrayList<List<Integer>> grid = new ArrayList<>();
        grid.add(row);
        grid.add(row);
        grid.add(row);
        grid.add(row);

        GameOfLife gameOfLife = new GameOfLife(grid);

        ArrayList<List<Integer>> resultList = gameOfLife.nextGeneration();
        for (List<Integer> newRow : resultList) {
            System.out.println(newRow);
        }
    }
}
