/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {

        InputConverter inputConverter = new InputConverter();

        System.out.println("First Generation");
        ArrayList<ArrayList<Integer>> firstGeneration;
        try {
            firstGeneration = inputConverter.reader();
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
        for (List<Integer> newRow : firstGeneration) {
            System.out.println(newRow);
        }

        GameOfLife gameOfLife = new GameOfLife();

        System.out.println("Next Generation");
        ArrayList<List<Integer>> nextGeneration = gameOfLife.nextGeneration();
        for (List<Integer> newRow : nextGeneration) {
            System.out.println(newRow);
        }
    }
}
